export const DOMstrings = {
    selector: '.selector',
    selectorActive: 'selector--active',
    selectorOption: '.selector__option',
    selectorOptionText: '.selector__option--all p',
    selectorOptionActive: '.selector__option--active',
    selectorOptionActiveClass: 'selector__option--active',
    openFilter: '.open-filter',
    closeFilter: '.filter__close-filters',
    backdrop: '.backdrop',
    filterMobile: '.filter-mobile',
    filterSize: '.filter__size',
    filterSizeSelected: 'filter__size--selected',
    filterFit: '.filter__fit-option',
    filterFitSelected: 'filter__fit-option--selected',
    filterColor: '.filter__color-option',
    filterColorSelected: 'filter__color-option--active',
    paginationLink: '.pagination__link',
    paginationLinkActive: 'pagination__link--active',
    arrowBack: '.pagination__arrow--prev',
    arrowNext: '.pagination__arrow--next',
    lowerPriceInRange: '.filter__price-number--lower',
    higherPriceInRange: '.filter__price-number--higher',
    emptyFilter: '.empty-filter-result',
    paginationContainer: '.pagination',
    cleanFilters: '.filter__button--clean',
    applyFilters: '.filter__button--apply',
    productSize: '.product-description__size',
    productColor: '.product-description__color',
    productSizeSelected: 'product-description__size--active',
    productColorSelected: 'product-description__color--active',
    burgerMenuIcon: '.navigation__burger-menu',
    burgerMenuContainer: '.vertical-menu',
    productImagesOptions: '.product-description__more-images-item',
    flippingImageArrowLeft: '.product-description__arrow--left',
    flippingImageArrowRight: '.product-description__arrow--right',
    imagesContainer: '#slider'


}

